In [1]:
print("Chikezie Chinweizu")

Chikezie Chinweizu


In [2]:
x="Boy"
type(x)

str

In [3]:
x=5000000
type(x)

int

In [5]:
x=5000+10000
print(x)
type(x)

15000


int

In [6]:
x=[8,10,99]
print(x)
type(x)

[8, 10, 99]


list

In [7]:
print(x[1])
print(x[2])

10
99


In [8]:
x[2]=50
print(x)

[8, 10, 50]


In [19]:
y=["Ada","Oluchi","Kambili","Kamnulia"]
type(y)
print(y)

['Ada', 'Oluchi', 'Kambili', 'Kamnulia']


In [20]:
print(y[1])

Oluchi


In [21]:
y[1]="Grace"
print(y)

['Ada', 'Grace', 'Kambili', 'Kamnulia']


In [17]:
x=(10,8,99)
print(x)

(10, 8, 99)


In [22]:
type(x)

tuple

In [23]:
(x,y,z)=("Kambili","Kamnulia","Oluoma")
print(x)
print(y)
print(z)

Kambili
Kamnulia
Oluoma


In [27]:
x=50
y=30
result=(x*y)
print(result)

1500


In [28]:
result=(x+y)
print(result)

80


In [29]:
var= "CHINWEIZU"
print(var[5])

E


In [30]:
print(var[7])

Z


In [34]:
print(var[0:4])

CHIN


In [35]:
print(var[5:])

EIZU


In [36]:
print(var[:7])

CHINWEI


In [37]:
print(var[:50])

CHINWEIZU


In [38]:
len(var)

9

In [1]:
num=2+5j
type(num)

complex

In [2]:
num.imag

5.0

In [3]:
num.real

2.0

In [6]:
x="192"
type(x)

str

In [7]:
int(x)

192

In [8]:
float(x)

192.0

In [9]:
complex(x)

(192+0j)

In [10]:
print(complex(8,99))

(8+99j)


In [12]:
import math
x=10
print(math.exp(x))

22026.465794806718


In [13]:
x=-25.4
print(abs(x))

25.4


In [14]:
math.pi

3.141592653589793

In [15]:
math.e

2.718281828459045

In [16]:
x=16
print(math.sqrt(x))

4.0


In [17]:
int(x)

16

In [1]:
num=[1,2,3,4]
print(num)

[1, 2, 3, 4]


In [2]:
letter=['a','b','c','d']
print(letter)

['a', 'b', 'c', 'd']


In [3]:
stg=['get','certified','get','ahead']
print(stg)

['get', 'certified', 'get', 'ahead']


In [4]:
mix=('1','6','Simplilearn','get','certified')
print(mix)

('1', '6', 'Simplilearn', 'get', 'certified')


In [6]:
mat=[['1','2'],['a','b']]
print(mat)

[['1', '2'], ['a', 'b']]


In [7]:
print(mix)

('1', '6', 'Simplilearn', 'get', 'certified')


In [8]:
mix[3]

'get'

In [10]:
mix[-2]

'get'

In [11]:
mix[0:3]

('1', '6', 'Simplilearn')

In [12]:
mix[2:4]

('Simplilearn', 'get')

In [13]:
mix[2:3]

('Simplilearn',)

In [14]:
mix[::2]

('1', 'Simplilearn', 'certified')

In [15]:
mix[::-1]

('certified', 'get', 'Simplilearn', '6', '1')

In [16]:
print(letter)

['a', 'b', 'c', 'd']


In [17]:
print(stg)

['get', 'certified', 'get', 'ahead']


In [18]:
conc=letter+stg
print(conc)

['a', 'b', 'c', 'd', 'get', 'certified', 'get', 'ahead']


In [3]:
var=list("hey baby")
print(var)

['h', 'e', 'y', ' ', 'b', 'a', 'b', 'y']


In [4]:
print(num)

NameError: name 'num' is not defined

In [5]:
num=(1,2,3,4)
print(num)

(1, 2, 3, 4)


In [7]:
one,*others=num
print(one)
print(others)

1
[2, 3, 4]


In [8]:
print(num)

(1, 2, 3, 4)


In [9]:
print(stg)

NameError: name 'stg' is not defined

In [10]:
stg=['get','certified','get','ahead']
print(stg)

['get', 'certified', 'get', 'ahead']


In [11]:
print(num)

(1, 2, 3, 4)


In [12]:
num.append(5)

AttributeError: 'tuple' object has no attribute 'append'

In [13]:
print(num)

(1, 2, 3, 4)


In [14]:
num.append(5)
print(num)

AttributeError: 'tuple' object has no attribute 'append'

In [15]:
num=[1,2,3,4]
print(num)

[1, 2, 3, 4]


In [16]:
num.append(5)
print(num)

[1, 2, 3, 4, 5]


In [17]:
print(stg)

['get', 'certified', 'get', 'ahead']


In [18]:
num.extend(stg)
print(num)

[1, 2, 3, 4, 5, 'get', 'certified', 'get', 'ahead']


In [19]:
num.insert(4,'Kambili')
print(num)

[1, 2, 3, 4, 'Kambili', 5, 'get', 'certified', 'get', 'ahead']


In [20]:
num.remove('Kambili')
print(num)

[1, 2, 3, 4, 5, 'get', 'certified', 'get', 'ahead']


In [21]:
var1=['b','f','a','q','r']
var1.sort()
print(var1)

['a', 'b', 'f', 'q', 'r']


In [22]:
x=[9,7,3,23,45,67,99,54]
len(x)

8

In [23]:
min(x)

3

In [24]:
max(x)

99

In [25]:
sum(x)

307

In [27]:
sum(x)//len(x)

38

In [2]:
emp=()
print(type(emp))

<class 'tuple'>


In [3]:
print(emp)

()


In [4]:
#Operations on Tuples.

In [3]:
city="Lagos",
print(type(city))

<class 'tuple'>


In [4]:
type(city)

tuple

In [5]:
city="lagos","owerri","zaria","ibadan"
city

('lagos', 'owerri', 'zaria', 'ibadan')

In [6]:
tuple1="1",'2','3','4'
tuple1.append(6)

AttributeError: 'tuple' object has no attribute 'append'

In [7]:
tuple1

('1', '2', '3', '4')

In [8]:
print(city)

('lagos', 'owerri', 'zaria', 'ibadan')


In [9]:
city(1)

TypeError: 'tuple' object is not callable

In [10]:
city[1]

'owerri'

In [11]:
city

('lagos', 'owerri', 'zaria', 'ibadan')

In [12]:
num=1,2,3,4
print(num)

(1, 2, 3, 4)


In [15]:
print(city+num)

('lagos', 'owerri', 'zaria', 'ibadan', 1, 2, 3, 4)


In [16]:
nest=(city,num)
print(nest)

(('lagos', 'owerri', 'zaria', 'ibadan'), (1, 2, 3, 4))


In [17]:
rep=('Kezie',)*10
print(rep)

('Kezie', 'Kezie', 'Kezie', 'Kezie', 'Kezie', 'Kezie', 'Kezie', 'Kezie', 'Kezie', 'Kezie')


In [20]:
rep=('Kezie',)
print(rep*10)

('Kezie', 'Kezie', 'Kezie', 'Kezie', 'Kezie', 'Kezie', 'Kezie', 'Kezie', 'Kezie', 'Kezie')


In [21]:
num

(1, 2, 3, 4)

In [22]:
num[2:]

(3, 4)

In [23]:
num[::-1]

(4, 3, 2, 1)

In [24]:
tuple('Kamnulia')

('K', 'a', 'm', 'n', 'u', 'l', 'i', 'a')

In [25]:
num

(1, 2, 3, 4)

In [26]:
a,b,c,d=num
print(a,b,c,d)

1 2 3 4


In [27]:
Lst=[1,2,3,4]
print(type(Lst))

<class 'list'>


In [28]:
tpl=tuple(Lst)
print(tpl)

(1, 2, 3, 4)


In [29]:
print(type(tpl))

<class 'tuple'>


In [31]:
lst=[(1,2,3,4),(4,5,6),]
print(lst)

[(1, 2, 3, 4), (4, 5, 6)]


In [32]:
lst.append(('chi','boy','genius'))
print(lst)

[(1, 2, 3, 4), (4, 5, 6), ('chi', 'boy', 'genius')]


In [34]:
tpl=(['a','b','c'],['d','e','f'])
print(tpl)

(['a', 'b', 'c'], ['d', 'e', 'f'])


In [35]:
tpl[1].append('i')
print(tpl)

(['a', 'b', 'c'], ['d', 'e', 'f', 'i'])


In [36]:
stg="tim's Birthday"
print(stg)

tim's Birthday


In [1]:
d1={}
print(d1)
print(type(d1))

{}
<class 'dict'>


In [2]:
d2={1:"Welcome",2:"to",3:"Norway",4:"Chikezie"}
print(d2)

{1: 'Welcome', 2: 'to', 3: 'Norway', 4: 'Chikezie'}


In [4]:
d3={"name":"SamKerr","age":23,"Career":"Football"}
print(d3)

{'name': 'SamKerr', 'age': 23, 'Career': 'Football'}


In [5]:
d5=dict([(1,"Welcome"),(2,"to"),(3,"Norway")])
print(d5)

{1: 'Welcome', 2: 'to', 3: 'Norway'}


In [6]:
d6={"name":{"first":"Sam","last":"Kerr"},"age":23,"Career":"Football"}
print(d6)

{'name': {'first': 'Sam', 'last': 'Kerr'}, 'age': 23, 'Career': 'Football'}


In [12]:
d={}
d[0]=("Welcome")
print(d)

{0: 'Welcome'}


In [13]:
d[1]=("How","are","you")
print(d)

{0: 'Welcome', 1: ('How', 'are', 'you')}


In [14]:
d["name"]=("Leo")
print(d)

{0: 'Welcome', 1: ('How', 'are', 'you'), 'name': 'Leo'}


In [15]:
d["name"]={"first":"Sam","last":"Kerr"}
print(d)

{0: 'Welcome', 1: ('How', 'are', 'you'), 'name': {'first': 'Sam', 'last': 'Kerr'}}


In [1]:
print(d)

NameError: name 'd' is not defined

In [2]:
d={0: 'Welcome', 1: ('How', 'are', 'you'), 'name': {'first': 'Sam', 'last': 'Kerr'}}
print(d)

{0: 'Welcome', 1: ('How', 'are', 'you'), 'name': {'first': 'Sam', 'last': 'Kerr'}}


In [5]:
print(d["name"])

{'first': 'Sam', 'last': 'Kerr'}


In [6]:
print(d["name"]["first"])

Sam


In [8]:
print(d.get(1))

('How', 'are', 'you')


In [9]:
print(d.get(2))

None


In [10]:
print(d.get("name"))

{'first': 'Sam', 'last': 'Kerr'}


In [11]:
print(d)

{0: 'Welcome', 1: ('How', 'are', 'you'), 'name': {'first': 'Sam', 'last': 'Kerr'}}


In [12]:
d.pop(0)

'Welcome'

In [13]:
print(d)

{1: ('How', 'are', 'you'), 'name': {'first': 'Sam', 'last': 'Kerr'}}


In [14]:
d.popitem("name")

TypeError: dict.popitem() takes no arguments (1 given)

In [15]:
d.popitem(1)

TypeError: dict.popitem() takes no arguments (1 given)

In [16]:
d.popitem()

('name', {'first': 'Sam', 'last': 'Kerr'})

In [17]:
print(d)

{1: ('How', 'are', 'you')}


In [18]:
d={0: 'Welcome', 1: ('How', 'are', 'you'), 'name': {'first': 'Sam', 'last': 'Kerr'}}
print(d)

{0: 'Welcome', 1: ('How', 'are', 'you'), 'name': {'first': 'Sam', 'last': 'Kerr'}}


In [19]:
d.values()

dict_values(['Welcome', ('How', 'are', 'you'), {'first': 'Sam', 'last': 'Kerr'}])

In [20]:
keys={'a','b','c','d'}
value=1
dict.fromkeys(keys,value)

{'a': 1, 'c': 1, 'b': 1, 'd': 1}

In [21]:
box={'a': 1, 'c': 1, 'b': 1, 'd': 1}
print(box)

{'a': 1, 'c': 1, 'b': 1, 'd': 1}


In [22]:
dict.sort(box)

AttributeError: type object 'dict' has no attribute 'sort'

In [24]:
s=set([1,2,3,4])
print(s)
print(type(s))

{1, 2, 3, 4}
<class 'set'>


In [25]:
s.add('NORWAY')
print(s)

{1, 2, 3, 4, 'NORWAY'}


In [29]:
s1=set([1,3,7,2])
s2=set([3,2,8,9])
s1.union(s2)

{1, 2, 3, 7, 8, 9}

In [30]:
s1.difference(s2)

{1, 7}

In [5]:
a=200
if a>100:
    print("This is the if body")
print("Try Again")

This is the if body
Try Again


In [10]:
i=27
if i % 2==0:
    print("This is the if block")
    print("Yes! i is an even number")
else:
    print("This is the else Block")
    print("i is an even number")

This is the else Block
i is an even number


In [12]:
c=100
if c<25:
    if c%2==0:
        print("C is an even number less than 25")
    else:
        print("C is an odd number less than 25")
else:
    print("C is greater than 25")

C is greater than 25


In [16]:
var="o"
if var=="a":
    print("This is the vowel a")
elif var=="e":
    print("This is the vowel e")
elif var=="i":
    print("This is the vowel i")
elif var=="o":
    print("This is the vowel o")
elif var=="u":
    print("This is the vowel u")
else:
    print("This is a Fucking Consonant!")

This is the vowel o


In [4]:
x='Hey there.how are you?'
for i in x:
    if i ==".":
        break
        print(i)

In [ ]:
#we back!

In [10]:
from array import*

arr= array("i",[1,2,3,4,5])
print(arr)

array('i', [1, 2, 3, 4, 5])


In [11]:
print(arr[3])

4


In [15]:
for i in arr:
    print(i, end=" ")

1 2 3 4 5 

In [16]:
arr.reverse()
print(arr)

array('i', [5, 4, 3, 2, 1])


In [3]:
import numpy as np

In [6]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
a[2]

3

In [4]:
import time
import sys

In [5]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
a.ndim

2

In [7]:
a.itemsize

4

In [8]:
a.shape

(3, 2)

In [9]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [10]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.complex)
a

C:\Users\USER\AppData\Local\Temp\ipykernel_10324\2231566742.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.array([[1,2],[3,4],[5,6]], dtype=np.complex)


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
print("Concatenation example:")
print(np.char.add(["hello","hi"], ["abc","xyz"]))

Concatenation example:
['helloabc' 'hixyz']


In [22]:
print(np.char.multiply("Hello ", 5))

Hello Hello Hello Hello Hello 


In [23]:
print(np.char.center("Hello",20, fillchar= "-"))

-------Hello--------


In [27]:
print(np.char.capitalize("Hello"))

Hello


In [28]:
print(np.char.title("i wiill be in europe soon."))

I Wiill Be In Europe Soon.


In [29]:
print(np.char.split("i wiill be in europe soon."))

['i', 'wiill', 'be', 'in', 'europe', 'soon.']


#Pandas Tutorial

In [1]:
import pandas as pd

In [3]:
arr=[1,2,3,4,5]
s1= pd.Series(arr)
arr
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
order=[1,2,3,4,5]
s2= pd.Series(arr,index=order)
s2

1    1
2    2
3    3
4    4
5    5
dtype: int64

In [5]:
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [7]:
#modify index

s1.index=["A","B","C","D","E"]
s1

A    1
B    2
C    3
D    4
E    5
dtype: int64